language: node_js
node_js: stable
cache:
  directories:
    - node_modules
    - $(npm root -g)
    - $(npm config get prefix)/bin/hexo
branches:
  only:
    - source
before_install:
  - git config --global user.name "Chs97"
  - git config --global user.email chsqaq@gmail.com
  - npm install hexo -g
script:
  - hexo g
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  - hexo d